version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    depends_on:
      - postgres
    ports:
      - "9081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: change_me

  chat-service:
    build: ./chat-service
    depends_on:
      - postgres
    ports:
      - "9082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: change_me

  gateway:
    build: ./gateway
    depends_on:
      - auth-service
      - chat-service
    ports:
      - "9080:8080"

volumes:
  pgdata:
