version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: change_me
    ports: [ "5432:5432" ]
    volumes: [ pgdata:/var/lib/postgresql/data ]

  auth-service:
    build: ./auth-service
    ports: [ "8081:8080" ]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: change_me
    depends_on: [ postgres ]

  chat-service:
    build: ./chat-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: change_me
    depends_on:
      - postgres

volumes:
  pgdata:
