name: spring-microservices
services:
  app:
    build:
      context: /home/frazerfrax1/spring-microservices
      dockerfile: Dockerfile
    container_name: spring-template-app
    depends_on:
      postgres:
        condition: service_started
        required: true
    environment:
      SPRING_DATASOURCE_PASSWORD: change_me
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: springuser
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: change_me
      POSTGRES_USER: springuser
    image: postgres:15
    networks:
      default: null
    restart: always
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume: {}
networks:
  default:
    name: spring-microservices_default
volumes:
  postgres-data:
    name: spring-microservices_postgres-data
