server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
