server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

# Additional port configuration for dual-port setup
---
spring:
  config:
    activate:
      on-profile: dual-port
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
server:
  port: 8082

logging:
  level:
    org.springframework.cloud.gateway: INFO
