name: build-auth-and-deploy
on:
  push:
    branches: [ main ]

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/auth-service:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '21' }
      - name: Test & package
        working-directory: auth-service
        run: ./mvnw -B verify
      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: auth-service
          push: true
          tags: ${{ env.IMAGE }}
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key:      ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /srv/spring-mono
            docker compose pull
            docker compose up -d --remove-orphans
