name: build-and-deploy-staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest    strategy:
      matrix:
        service:
          - auth-service
          - gateway-service # Add gateway-service to the matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login al registry GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Rendi eseguibile mvnw per ${{ matrix.service }}
        run: |
          if [ "${{ matrix.service }}" = "gateway-service" ]; then
            chmod +x gateway/initial/mvnw
          else
            chmod +x ${{ matrix.service }}/mvnw
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Test & package ${{ matrix.service }}
        working-directory: ${{ matrix.service == 'gateway-service' && 'gateway/initial' || matrix.service }}
        run: ./mvnw -B verify

      - name: Build & push image per ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          # Per gateway-service usiamo ./gateway come context e ./gateway/Dockerfile
          context: ${{ matrix.service == 'gateway-service' && './gateway' || matrix.service }}
          file:    ${{ matrix.service == 'gateway-service' && './gateway/Dockerfile' || '' }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepara chiave SSH
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Deploy via SSH
        run: |
          ssh -i /home/runner/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            frazerfrax1@${{ secrets.DEPLOY_HOST }} \
            "cd /home/frazerfrax1/spring-mono && \
             docker compose -f docker-compose.staging.yml pull && \
             docker compose -f docker-compose.staging.yml up -d --remove-orphans"
